name: "Prettier Auto-Format"

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop

jobs:
  format:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        branch: [main, develop] # 👈 iterate over both branches

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ matrix.branch }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.15.0"

      - name: Install dependencies
        run: npm ci

      - name: Configure git
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Pull latest
        run: git pull origin ${{ matrix.branch }}

      - name: Generate timestamp
        id: vars
        run: echo "BRANCH_SUFFIX=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: Create and switch to new branch
        run: git checkout -b auto/format-${{ matrix.branch }}-${{ env.BRANCH_SUFFIX }}

      - name: Auto-fix formatting
        run: npx prettier --write "**/*.{js,ts,jsx,tsx,json,css,scss,md}"

      - name: Stage changes
        run: |
          git add . -- ':!package-lock.json'

      - name: Commit changes
        run: |
          git commit -m "chore: auto-format code with Prettier" || echo "No changes to commit"

      - name: Push branch
        run: git push origin auto/format-${{ matrix.branch }}-${{ env.BRANCH_SUFFIX }}

      - name: Create Pull Request
        id: create_pr
        run: |
          PR_URL=$(gh pr create \
            --title "chore: auto-format (${{ matrix.branch }})" \
            --body "Automatic code formatting via Prettier for ${{ matrix.branch }}." \
            --head auto/format-${{ matrix.branch }}-${{ env.BRANCH_SUFFIX }} \
            --base ${{ matrix.branch }})
          echo "PR_URL=$PR_URL" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Squash and merge PR
        if: env.PR_URL != ''
        run: |
          gh pr merge "$PR_URL" --squash --delete-branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
